/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:28ff9cfa-99f1-4663-b881-fd9538e25d7f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_59vvLbe3h",
    "aws_user_pools_web_client_id": "bcpg6njfja91mqk8893844n4d",
    "oauth": {
        "domain": "opencity-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4001/",
        "redirectSignOut": "http://localhost:4001/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://liee2nyajrge3g3fxzuv6ajfam.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
